version: '3'
services:
  auth-server:
    image: auth-server
    container_name: auth-server
    ports:
      - '9000:9000'
    networks:
      - likedin-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/login']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  browser-client:
    image: browser-client
    container_name: browser-client
    ports:
      - '9090:9090'
    networks:
      - likedin-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: on-failure
    depends_on:
      - auth-server

  posts:
    image: posts
    container_name: posts
    ports:
      - '7000:7000'
    networks:
      - likedin-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: on-failure
    depends_on:
      - auth-server

networks:
  likedin-network:
    driver: bridge
